ALTER TABLE businesses
ADD COLUMN IF NOT EXISTS bank_name TEXT,
ADD COLUMN IF NOT EXISTS account_name TEXT,
ADD COLUMN IF NOT EXISTS iban TEXT,
ADD COLUMN IF NOT EXISTS swift TEXT,
ADD COLUMN IF NOT EXISTS payment_instructions TEXT,
ADD COLUMN IF NOT EXISTS quote_prefix TEXT NOT NULL DEFAULT 'QUO-',
ADD COLUMN IF NOT EXISTS next_quote_number INTEGER NOT NULL DEFAULT 1,
ADD COLUMN IF NOT EXISTS default_language TEXT NOT NULL DEFAULT 'en'