ALTER TABLE invoices
ADD COLUMN IF NOT EXISTS public_token UUID NOT NULL DEFAULT gen_random_uuid(),
ADD COLUMN IF NOT EXISTS share_enabled BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN IF NOT EXISTS template_key TEXT NOT NULL DEFAULT 'classic',
ADD COLUMN IF NOT EXISTS invoice_format TEXT NOT NULL DEFAULT 'full',
ADD COLUMN IF NOT EXISTS discount_type TEXT NOT NULL DEFAULT 'fixed',
ADD COLUMN IF NOT EXISTS discount_value NUMERIC(14,3) NOT NULL DEFAULT 0