ALTER TABLE businesses
ADD COLUMN IF NOT EXISTS invoice_accent TEXT NOT NULL DEFAULT '#0e7568',
ADD COLUMN IF NOT EXISTS invoice_font TEXT NOT NULL DEFAULT 'inter',
ADD COLUMN IF NOT EXISTS invoice_footer TEXT,
ADD COLUMN IF NOT EXISTS hide_platform_branding BOOLEAN NOT NULL DEFAULT false